services:
  - type: web
    name: gemini-fastapi-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    branch: main  # or your actual branch name
    autoDeploy: true

    envVars:
      - key: GOOGLE_API_KEY
        value: YOUR_API_KEY_HERE  # Replace only for local testing. On Render, set via Dashboard instead.
